### ISSUE TITLE
Items on soul sand disappear

### ISSUE THREAD

**Issue by FighterX9** [gliscowo/interactic#4] opened 2021-12-09 13:41 UTC
They just sink into the sand itself and cannot be seen anymore.
![image](https://user-images.githubusercontent.com/91667788/145406970-96ae7f0d-1731-44d7-9c50-3c9a76097898.png)

**Comment by gliscowo** [comment] 2022-01-17 20:53
Because the model of Soul Sand does not match up with its hitbox, this is expected behaviour. While it could technically be mitigated with special case for Soul Sand, this is not something I would want to introduce for the sake of consistency. Because consider another mod adds their own Soul Sand or something else which does not line its model up with the hitbox. It will then become inconsistent which blocks will still show the item and which won't. For these reasons, I will now go ahead and close this

**Closed as completed by gliscowo** 2022-01-17 20:53 UTC
