### ISSUE TITLE
Items phasing through floor when thrown.

### ISSUE THREAD

**Issue by theDerxu** [gliscowo/interactic#6] opened 2022-01-23 19:46 UTC
I have a few texture packs on with special textures and it seems they go into the block I throw them onto, Also any items with models that are big seem to get spun like crazy in the air, some sides of 3d hand held items are also just invisible. Please fix these :)

**Comment by Noaaan** [comment] 2022-01-23 20:41
Could you provide the name of the texture pack you are using? Most vanilla/modded blocks and items seem to work as intended. If any of your items are going invisible it might be a mod conflict instead of a texture pack issue, but it isn't easy to say

**Comment by theDerxu** [comment] 2022-01-23 21:01
Faithless, It seems to be the torches that are broken, I fixed the clipping through walls with another pack. Just the torches get flung when thrown and one side being invisible.
I am trying to fix it by changing the pack rather than the mod rn, but It might not work.

**Comment by theDerxu** [comment] 2022-01-28 11:35
Nvm phasing through floor has broke again, @Noaaan

**Comment by gliscowo** [comment] 2022-03-17 08:17
As this is not an issue that's really fixable from the Interactic's side without introducing a significant amount of special handling that will never catch all edge-cases, I will go ahead an close this for now. Feel free to provide us with a link to the resource pack(s) you were having problems with, we might look into it in the future
Cheers

**Closed as completed by gliscowo** 2022-03-17 08:17 UTC
Labels: status: wontfix
